version: "3"

services:
    project_triangle_db:
        image: postgres:10.0
        container_name: project_triangle_db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: project_triangle_dev

    project_triangle:
        container_name: project_triangle
        build: .
        links:
            - project_triangle_db
        ports:
            - 4000:4000
